name: test

"on":
  pull_request:
    branches: [main]
  workflow_call:
    secrets:
      GCLOUD_PROJECT:
        required: true
      GCLOUD_SA_KEY:
        required: true
  repository_dispatch:
    types: [test]

env:
  KCIDB_IO_URL: kcidb-io@git+https://github.com/kernelci/kcidb-io.git@${{ github.event.client_payload.kcidb_io_ref || 'main' }}

jobs:
  check_python:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          cache: 'pip'
          python-version: ${{ matrix.python-version }}
      - name: Check setup.py and requirements.txt are consistent
        run: |
          # Check both install_requires in setup.py and requirements.txt contain
          # the same dependencies
          (
            set -e -u -o pipefail
            unique_requires=$({
              sed -n '/install_requires=/,/],/ s/.*"\([^"]\+\)".*/\1/p' setup.py |
                sort -u
              grep -v '^#' requirements.txt |
                sort -u
            } | sort | uniq -u)
            if [ -n "$unique_requires" ]; then
              echo "Requirements not both in setup.py and requirements.txt:" >&2
              echo "$unique_requires" >&2
              false
            fi
          )
      - name: Install
        run: |
          python -m pip install --upgrade pip setuptools
          sed -i -e "s|kcidb-io@[^\"]*|${KCIDB_IO_URL}|" requirements.txt setup.py
          pip3 install --upgrade '.[dev]'
      - name: Check python sources with flake8
        run: "flake8 kcidb *.py"
        env:
          KCIDB_HOOKS: "pre-commit"
      - name: Check python sources with pylint
        run: "pylint kcidb *.py"
        env:
          KCIDB_HOOKS: "pre-commit"
      - name: Test with pytest
        run: |
          KCIDB_IO_HEAVY_ASSERTS=1 KCIDB_HEAVY_ASSERTS=1 \
            pytest --tb=native --durations=0 --durations-min=1
        env:
          KCIDB_HOOKS: "pre-commit"
          PYTHONWARNINGS: "ignore:pkg_resources is deprecated:UserWarning"

  check_auxiliary_files:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          python -m pip install --upgrade pip setuptools
          sed -i -e "s|kcidb-io@[^\"]*|${KCIDB_IO_URL}|" requirements.txt setup.py
          pip3 install --upgrade '.[dev]'
      - name: Check YAML files with yamllint
        run: find -name '*.yaml' -or -name '*.yml' | xargs yamllint
        env:
          KCIDB_HOOKS: "pre-commit"
      - name: Check test catalog is ordered alphabetically
        run: |
          test_list=$(
              python3 <(
                  echo "import sys, yaml"
                  echo "for k in yaml.safe_load(sys.stdin).keys():"
                  echo "    print(k)"
              ) < tests.yaml
          )
          export LANG=C
          test_list_diff=$(diff -u <(echo "$test_list") \
                                   <(echo "$test_list" | sort)) ||
              {
                  echo "Tests out of alphabetic order." >&2
                  echo "Change the order as below:" >&2
                  echo "$test_list_diff" >&2
                  false
              }
        env:
          KCIDB_HOOKS: "pre-commit"
      - name: Validate test catalog
        run: kcidb-tests-validate --urls < tests.yaml
